language: python
cache: pip

python:
  - '2.7'
  - '3.4'
  - '3.5'
  - '3.6'

install: pip install tox

script:
  - 'tox'

matrix:
  fast_finish: true
  include:
    # One-off runs
    - python: '3.6'
      env: TOXENV=coverage
    - python: '3.6'
      env: TOXENV=black
    - python: '3.5'  # 3.6 after https://github.com/PyCQA/pylint/issues/1113
      env: TOXENV=pylint

# This is required to enable container based Travis CI infrastructure.
# See http://docs.travis-ci.com/user/migrating-from-legacy/
sudo: false
