dist: xenial
language: python
cache: pip

# Drop once EOL: https://devguide.python.org/#status-of-python-branches
python:
  - '2.7'
  - '3.5'
  - '3.6'

install: pip install tox
script:
  - 'tox'

matrix:
  include:
    - python: '3.7'
      env: TOXENV=py37,black,pylint,coverage
