dist: xenial  # needed for python 3.7+
language: python
cache: pip

python:
  - '2.7'
  - '3.4'
  - '3.5'
  - '3.6'
  - '3.7'

install: pip install tox

script:
  - 'tox'

matrix:
  fast_finish: true
  include:
    # One-off runs
    - python: '3.7'
      env: TOXENV=coverage
    - python: '3.7'
      env: TOXENV=black
    - python: '3.7'
      env: TOXENV=pylint
